from PIL import Image
import os
import glob

# 用户选定风格后生成的功能地图图标总图（4 列 x 2 行）
SRC = sorted(glob.glob('g:/CoodBuddy_work/HBv1.0/concept/icons-map/*.png'))[-1]
OUT_DIR = 'g:/CoodBuddy_work/HBv1.0/src/assets/icons-map'

# 8 格对应：7 个功能组 + 1 个占位
NAMES = [
    ('image', 'image'),
    ('video', 'video'),
    ('audio', 'audio'),
    ('script', 'script'),
    ('character', 'character'),
    ('imgtools', 'imgtools'),
    ('vidtools', 'vidtools'),
    ('extra', 'extra'),
]

COLS, ROWS = 4, 2
TARGET_SIZE = 128
BRIGHT_THRESHOLD = 70


def main():
    img = Image.open(SRC).convert('RGBA')
    cell_w = img.width / COLS
    cell_h = img.height / ROWS
    crop_size = int(min(cell_w, cell_h) * 0.90)
    os.makedirs(OUT_DIR, exist_ok=True)

    imports = []
    entries = []

    for idx, (id_, base) in enumerate(NAMES):
        col = idx % COLS
        row = idx // COLS
        cx = (col + 0.5) * cell_w
        cy = (row + 0.5) * cell_h
        left = int(cx - crop_size / 2)
        upper = int(cy - crop_size / 2)
        cell = img.crop((left, upper, left + crop_size, upper + crop_size)).copy()

        px = cell.load()
        for y in range(cell.height):
            for x in range(cell.width):
                r, g, b, a = px[x, y]
                if max(r, g, b) < BRIGHT_THRESHOLD:
                    px[x, y] = (0, 0, 0, 0)

        bbox = cell.getbbox()
        if bbox:
            pad = int(crop_size * 0.04)
            x1 = max(0, bbox[0] - pad)
            y1 = max(0, bbox[1] - pad)
            x2 = min(cell.width, bbox[2] + pad)
            y2 = min(cell.height, bbox[3] + pad)
            cell = cell.crop((x1, y1, x2, y2))

        cell.thumbnail((TARGET_SIZE, TARGET_SIZE), Image.LANCZOS)
        out = Image.new('RGBA', (TARGET_SIZE, TARGET_SIZE), (0, 0, 0, 0))
        x = (TARGET_SIZE - cell.width) // 2
        y = (TARGET_SIZE - cell.height) // 2
        out.paste(cell, (x, y), cell)

        filename = f'icon_map_{idx:02d}_{base}.png'
        path = os.path.join(OUT_DIR, filename)
        out.save(path)
        print(f'wrote {path}')

        var_name = f'icon_map_{idx:02d}_{base}'
        imports.append(f"import {var_name} from './{filename}';")
        entries.append(f"  {id_}: {var_name},")

    index_path = os.path.join(OUT_DIR, 'index.ts')
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by scripts/slice-map-icons.py\n')
        f.write('\n'.join(imports) + '\n\n')
        f.write('export const MAP_ICONS: Record<string, string> = {\n')
        f.write('\n'.join(entries) + '\n')
        f.write('};\n')
    print(f'wrote {index_path}')


if __name__ == '__main__':
    main()
