from PIL import Image
import os

# 输入：用户选定的原始图标总图（5 列 x 4 行网格）
SRC = 'g:/CoodBuddy_work/HBv1.0/concept/icons3/An_app_icon_set_sheet_designed_2026-08-30T01-34-55.png'
OUT_DIR = 'g:/CoodBuddy_work/HBv1.0/src/assets/icons'

# 顺序：品牌 + 10 个功能入口 + 9 个导演流程
NAMES = [
    ('brand', 'brand'),
    ('home', 'home'),
    ('image', 'image'),
    ('video', 'video'),
    ('audio', 'audio'),
    ('imgtools', 'imgtools'),
    ('vidtools', 'vidtools'),
    ('canvas', 'canvas'),
    ('assets', 'assets'),
    ('projects', 'projects'),
    ('settings', 'settings'),
    ('idea', 'idea'),
    ('plan', 'plan'),
    ('script', 'script'),
    ('asset', 'asset'),
    ('shot', 'shot'),
    ('prompt', 'prompt'),
    ('generate', 'generate'),
    ('edit', 'edit'),
    ('deliver', 'deliver'),
]

COLS, ROWS = 5, 4
TARGET_SIZE = 128
BRIGHT_THRESHOLD = 70  # 通道最大值低于此 -> 视为背景/边框，置透明


def main():
    img = Image.open(SRC).convert('RGBA')
    # 按单元格中心裁剪，避免 1024 不能被 5 整除导致的边缘裁切问题
    cell_w = img.width / COLS
    cell_h = img.height / ROWS
    crop_size = int(min(cell_w, cell_h) * 0.96)
    os.makedirs(OUT_DIR, exist_ok=True)

    imports = []
    entries = []

    for idx, (id_, base) in enumerate(NAMES):
        col = idx % COLS
        row = idx // COLS
        cx = (col + 0.5) * cell_w
        cy = (row + 0.5) * cell_h
        left = int(cx - crop_size / 2)
        upper = int(cy - crop_size / 2)
        cell = img.crop((left, upper, left + crop_size, upper + crop_size)).copy()

        # 去除深色背景和图块细边框：暗像素置透明
        px = cell.load()
        for y in range(cell.height):
            for x in range(cell.width):
                r, g, b, a = px[x, y]
                if max(r, g, b) < BRIGHT_THRESHOLD:
                    px[x, y] = (0, 0, 0, 0)

        # 裁切到内容
        bbox = cell.getbbox()
        if bbox:
            pad = int(crop_size * 0.04)
            x1 = max(0, bbox[0] - pad)
            y1 = max(0, bbox[1] - pad)
            x2 = min(cell.width, bbox[2] + pad)
            y2 = min(cell.height, bbox[3] + pad)
            cell = cell.crop((x1, y1, x2, y2))

        # 等比缩放到 128x128 画布，居中，保持透明底
        cell.thumbnail((TARGET_SIZE, TARGET_SIZE), Image.LANCZOS)
        out = Image.new('RGBA', (TARGET_SIZE, TARGET_SIZE), (0, 0, 0, 0))
        x = (TARGET_SIZE - cell.width) // 2
        y = (TARGET_SIZE - cell.height) // 2
        out.paste(cell, (x, y), cell)

        filename = f'icon_{idx:02d}_{base}.png'
        path = os.path.join(OUT_DIR, filename)
        out.save(path)
        print(f'wrote {path}')

        var_name = f'icon_{idx:02d}_{base}'
        imports.append(f"import {var_name} from './{filename}';")
        entries.append(f"  {id_}: {var_name},")

    # 自动生成 index.ts
    index_path = os.path.join(OUT_DIR, 'index.ts')
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by scripts/slice-icons.py\n')
        f.write('\n'.join(imports) + '\n\n')
        f.write('export const ICONS: Record<string, string> = {\n')
        f.write('\n'.join(entries) + '\n')
        f.write('};\n')
    print(f'wrote {index_path}')


if __name__ == '__main__':
    main()
